import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { QueryProvider } from "@/client/providers/QueryProvider";
import { GlobalNav } from "@/components/layout/GlobalNav";
import { BottomTabBar } from "@/components/layout/BottomTabBar";
import { FixedCTA } from "@/components/layout/FixedCTA";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-background text-text-primary">
        <QueryProvider>
          <GlobalNav />
          <main className="flex-1 pb-16 md:pb-0">
            {children}
          </main>
          <FixedCTA />
          <BottomTabBar />
        </QueryProvider>
      </body>
    </html>
  );
}
